version: '3'
services:

  postgres:
    image: postgres

  django:
    container_name: UrTracker
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - postgres

volumes:
  data: