# Generated by Django 2.0.7 on 2019-02-14 11:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('over_all_feeling', models.CharField(max_length=200)),
                ('workout', models.BooleanField()),
                ('workout_type', models.CharField(max_length=200)),
                ('headspace', models.BooleanField()),
                ('sad_lamp', models.BooleanField()),
                ('vitd', models.BooleanField()),
                ('omega3', models.BooleanField()),
                ('conflict', models.BooleanField()),
                ('accomplish', models.BooleanField()),
                ('sleep', models.IntegerField()),
                ('eating', models.TextField()),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackdata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
